# Generated by Django 6.0.7 on 2026-07-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tshirt', 'T-shirts'), ('longsleeve', 'Långärmade & Hoodies'), ('poster', 'Posters'), ('vinyl', 'Vinyl & Specialutgåvor')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
            ],
        ),
    ]
