# Generated by Django 6.0.7 on 2026-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-shirts'), ('longsleeve', 'Longsleeve & Hoodies'), ('poster', 'Posters'), ('vinyl', 'Vinyl & Special Editions')], max_length=20),
        ),
    ]
